# Generated by Django 5.1.1 on 2024-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=72)),
                ('senha', models.CharField(max_length=72)),
                ('previlegio', models.CharField(max_length=72)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Usuários',
                'db_table_comment': 'Usuarios do sistema',
            },
        ),
    ]
