# Generated by Django 5.1.1 on 2024-09-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=72)),
                ('telefone', models.CharField(max_length=72)),
                ('email', models.CharField(default='Cadastrar', max_length=128)),
                ('fluxo', models.CharField(max_length=72)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Clientes',
                'db_table_comment': 'Clientes que entraram em contato via whatsapp',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=72)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=72)),
                ('senha', models.CharField(max_length=72)),
                ('previlegio', models.CharField(max_length=72)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Usuários',
                'db_table_comment': 'Usuarios do sistema',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('remetente', models.CharField(max_length=72, verbose_name='cliente')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boot.cliente')),
            ],
            options={
                'verbose_name': 'Mensagens',
                'db_table_comment': 'Mensagens recebias e enviadas para os clientes',
                'ordering': ['date_created'],
            },
        ),
    ]
