# Generated by Django 5.1.1 on 2024-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0002_delete_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fluxo',
            field=models.CharField(default='Inicial', max_length=72),
        ),
    ]
