# Generated by Django 5.1.1 on 2024-10-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boot', '0003_alter_cliente_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(blank=True, max_length=72),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='notificacao',
            field=models.BooleanField(default=False),
        ),
    ]
